name: Automated Analysis

on:
  push:
  pull_request:
  workflow_dispatch: # Allows you to manually trigger it anytime

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Run Linting
        run: npm run lint || echo "Linting issues found!"

      - name: Run Tests
        run: npm test || echo "Some tests failed!"
